// <auto-generated />
namespace FantasyTracker.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addedteamforfantasyteamnameandplayertableforroster : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedteamforfantasyteamnameandplayertableforroster));
        
        string IMigrationMetadata.Id
        {
            get { return "201703080011199_added team for fantasy team name and player table for roster"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
